import { Montserrat } from "next/font/google";
import "./globals.css";
import { Providers } from "@/store/Providers";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}  antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
